# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 01:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrongLifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_at', models.DateField(default=datetime.datetime.now)),
                ('exercise_name', models.CharField(max_length=200)),
                ('exercise_sets', models.IntegerField(default=0)),
                ('exercise_reps', models.IntegerField(default=0)),
                ('exercise_weight', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
