# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strong_lifts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stronglifts',
            old_name='add_at',
            new_name='added_at',
        ),
    ]
