# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strong_lifts', '0002_auto_20160131_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='stronglifts',
            name='edited_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
